name: Generate Docs

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "README.md"
      - "package.json"
      - "tsconfig-typedoc.json"
      - ".github/workflows/generate-docs.yml"

defaults:
  run:
    shell: bash

# We only want to run one job at a time in this group
concurrency:
  group: api-sdk-docs
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: docs-html
